apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: dev
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest: 
      memory: 256Mi
      cpu: 0.5
    max:
      memory: 1G
      cpu: 1
    min:
      memory: 100Mi
      cpu: 0.1
    type: Container
